export const basketball = {
  id: "basketball",
  label: "Basketball",
  icon: "🏀",
  gradient: "from-orange-400 to-amber-600",
  tagline: "Points, rebounds, assists, and more for your basketball team.",
  stats: [
    { key: "kills", label: "Points", agg: "sum" },
    { key: "digs", label: "Rebounds", agg: "sum" },
    { key: "assists", label: "Assists", agg: "sum" },
    { key: "errors", label: "Turnovers", agg: "sum" },
    { key: "aces", label: "Steals", agg: "sum" },
    { key: "blocks", label: "Blocks", agg: "sum" },
    { key: "hits", label: "Fouls", agg: "sum" },
  ],
  leaderboardColumns: ["kills", "digs", "assists", "aces", "blocks"],
  trendMetric: (row) => row.kills || 0,
  positions: ["Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center"],
  playersCardIcon: "🏀",
  scoreLabel: "Points",
  aiSportName: "basketball",
};
