export const soccer = {
  id: "soccer",
  label: "Soccer",
  icon: "⚽",
  gradient: "from-emerald-400 to-green-700",
  tagline: "Goals, assists, and recovery tools for your soccer squad.",
  stats: [
    { key: "kills", label: "Goals", agg: "sum" },
    { key: "assists", label: "Assists", agg: "sum" },
    { key: "goals_assists_avg", label: "G+A Avg", agg: "computed", editable: false, decimals: 1 },
    { key: "hits", label: "Shots", agg: "sum" },
    { key: "aces", label: "Shots on Target", agg: "sum" },
    { key: "service_receptions", label: "Pass Completion %", agg: "avg", suffix: "%", max: 100 },
    { key: "interceptions", label: "Interceptions", agg: "sum" },
    { key: "digs", label: "Saves", agg: "sum" },
    { key: "yellow_cards", label: "Yellow Cards", agg: "sum" },
    { key: "red_cards", label: "Red Cards", agg: "sum" },
  ],
  leaderboardColumns: ["kills", "assists", "hits", "interceptions", "digs"],
  trendMetric: (row) => (row.kills || 0) + (row.assists || 0),
  positions: ["Goalkeeper", "Center Back", "Full Back", "Defensive Mid", "Central Mid", "Winger", "Striker"],
  playersCardIcon: "⚽",
  scoreLabel: "Goals",
  aiSportName: "soccer",
};
